/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cubecalc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cubecalc.pb-c.h"
void   saved_rect__init
                     (SavedRect         *message)
{
  static const SavedRect init_value = SAVED_RECT__INIT;
  *message = init_value;
}
size_t saved_rect__get_packed_size
                     (const SavedRect *message)
{
  assert(message->base.descriptor == &saved_rect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t saved_rect__pack
                     (const SavedRect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &saved_rect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t saved_rect__pack_to_buffer
                     (const SavedRect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &saved_rect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SavedRect *
       saved_rect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SavedRect *)
     protobuf_c_message_unpack (&saved_rect__descriptor,
                                allocator, len, data);
}
void   saved_rect__free_unpacked
                     (SavedRect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &saved_rect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   saved_node_data__init
                     (SavedNodeData         *message)
{
  static const SavedNodeData init_value = SAVED_NODE_DATA__INIT;
  *message = init_value;
}
size_t saved_node_data__get_packed_size
                     (const SavedNodeData *message)
{
  assert(message->base.descriptor == &saved_node_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t saved_node_data__pack
                     (const SavedNodeData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &saved_node_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t saved_node_data__pack_to_buffer
                     (const SavedNodeData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &saved_node_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SavedNodeData *
       saved_node_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SavedNodeData *)
     protobuf_c_message_unpack (&saved_node_data__descriptor,
                                allocator, len, data);
}
void   saved_node_data__free_unpacked
                     (SavedNodeData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &saved_node_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   saved_comment__init
                     (SavedComment         *message)
{
  static const SavedComment init_value = SAVED_COMMENT__INIT;
  *message = init_value;
}
size_t saved_comment__get_packed_size
                     (const SavedComment *message)
{
  assert(message->base.descriptor == &saved_comment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t saved_comment__pack
                     (const SavedComment *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &saved_comment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t saved_comment__pack_to_buffer
                     (const SavedComment *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &saved_comment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SavedComment *
       saved_comment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SavedComment *)
     protobuf_c_message_unpack (&saved_comment__descriptor,
                                allocator, len, data);
}
void   saved_comment__free_unpacked
                     (SavedComment *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &saved_comment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   saved_result__init
                     (SavedResult         *message)
{
  static const SavedResult init_value = SAVED_RESULT__INIT;
  *message = init_value;
}
size_t saved_result__get_packed_size
                     (const SavedResult *message)
{
  assert(message->base.descriptor == &saved_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t saved_result__pack
                     (const SavedResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &saved_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t saved_result__pack_to_buffer
                     (const SavedResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &saved_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SavedResult *
       saved_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SavedResult *)
     protobuf_c_message_unpack (&saved_result__descriptor,
                                allocator, len, data);
}
void   saved_result__free_unpacked
                     (SavedResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &saved_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   saved_node__init
                     (SavedNode         *message)
{
  static const SavedNode init_value = SAVED_NODE__INIT;
  *message = init_value;
}
size_t saved_node__get_packed_size
                     (const SavedNode *message)
{
  assert(message->base.descriptor == &saved_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t saved_node__pack
                     (const SavedNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &saved_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t saved_node__pack_to_buffer
                     (const SavedNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &saved_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SavedNode *
       saved_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SavedNode *)
     protobuf_c_message_unpack (&saved_node__descriptor,
                                allocator, len, data);
}
void   saved_node__free_unpacked
                     (SavedNode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &saved_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   saved_connection__init
                     (SavedConnection         *message)
{
  static const SavedConnection init_value = SAVED_CONNECTION__INIT;
  *message = init_value;
}
size_t saved_connection__get_packed_size
                     (const SavedConnection *message)
{
  assert(message->base.descriptor == &saved_connection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t saved_connection__pack
                     (const SavedConnection *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &saved_connection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t saved_connection__pack_to_buffer
                     (const SavedConnection *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &saved_connection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SavedConnection *
       saved_connection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SavedConnection *)
     protobuf_c_message_unpack (&saved_connection__descriptor,
                                allocator, len, data);
}
void   saved_connection__free_unpacked
                     (SavedConnection *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &saved_connection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   saved_bucket__init
                     (SavedBucket         *message)
{
  static const SavedBucket init_value = SAVED_BUCKET__INIT;
  *message = init_value;
}
size_t saved_bucket__get_packed_size
                     (const SavedBucket *message)
{
  assert(message->base.descriptor == &saved_bucket__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t saved_bucket__pack
                     (const SavedBucket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &saved_bucket__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t saved_bucket__pack_to_buffer
                     (const SavedBucket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &saved_bucket__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SavedBucket *
       saved_bucket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SavedBucket *)
     protobuf_c_message_unpack (&saved_bucket__descriptor,
                                allocator, len, data);
}
void   saved_bucket__free_unpacked
                     (SavedBucket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &saved_bucket__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   saved_preset__init
                     (SavedPreset         *message)
{
  static const SavedPreset init_value = SAVED_PRESET__INIT;
  *message = init_value;
}
size_t saved_preset__get_packed_size
                     (const SavedPreset *message)
{
  assert(message->base.descriptor == &saved_preset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t saved_preset__pack
                     (const SavedPreset *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &saved_preset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t saved_preset__pack_to_buffer
                     (const SavedPreset *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &saved_preset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SavedPreset *
       saved_preset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SavedPreset *)
     protobuf_c_message_unpack (&saved_preset__descriptor,
                                allocator, len, data);
}
void   saved_preset__free_unpacked
                     (SavedPreset *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &saved_preset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   saved_globals__init
                     (SavedGlobals         *message)
{
  static const SavedGlobals init_value = SAVED_GLOBALS__INIT;
  *message = init_value;
}
size_t saved_globals__get_packed_size
                     (const SavedGlobals *message)
{
  assert(message->base.descriptor == &saved_globals__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t saved_globals__pack
                     (const SavedGlobals *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &saved_globals__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t saved_globals__pack_to_buffer
                     (const SavedGlobals *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &saved_globals__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SavedGlobals *
       saved_globals__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SavedGlobals *)
     protobuf_c_message_unpack (&saved_globals__descriptor,
                                allocator, len, data);
}
void   saved_globals__free_unpacked
                     (SavedGlobals *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &saved_globals__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor saved_rect__field_descriptors[4] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedRect, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedRect, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedRect, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedRect, h),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned saved_rect__field_indices_by_name[] = {
  3,   /* field[3] = h */
  2,   /* field[2] = w */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange saved_rect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor saved_rect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SavedRect",
  "SavedRect",
  "SavedRect",
  "",
  sizeof(SavedRect),
  4,
  saved_rect__field_descriptors,
  saved_rect__field_indices_by_name,
  1,  saved_rect__number_ranges,
  (ProtobufCMessageInit) saved_rect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor saved_node_data__field_descriptors[3] =
{
  {
    "bounds",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SavedNodeData, bounds),
    &saved_rect__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valueLo",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedNodeData, valuelo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valueHi",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedNodeData, valuehi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned saved_node_data__field_indices_by_name[] = {
  0,   /* field[0] = bounds */
  2,   /* field[2] = valueHi */
  1,   /* field[1] = valueLo */
};
static const ProtobufCIntRange saved_node_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor saved_node_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SavedNodeData",
  "SavedNodeData",
  "SavedNodeData",
  "",
  sizeof(SavedNodeData),
  3,
  saved_node_data__field_descriptors,
  saved_node_data__field_indices_by_name,
  1,  saved_node_data__number_ranges,
  (ProtobufCMessageInit) saved_node_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor saved_comment__field_descriptors[1] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SavedComment, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned saved_comment__field_indices_by_name[] = {
  0,   /* field[0] = text */
};
static const ProtobufCIntRange saved_comment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor saved_comment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SavedComment",
  "SavedComment",
  "SavedComment",
  "",
  sizeof(SavedComment),
  1,
  saved_comment__field_descriptors,
  saved_comment__field_indices_by_name,
  1,  saved_comment__number_ranges,
  (ProtobufCMessageInit) saved_comment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor saved_result__field_descriptors[2] =
{
  {
    "page",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedResult, page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "perPage",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedResult, perpage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned saved_result__field_indices_by_name[] = {
  0,   /* field[0] = page */
  1,   /* field[1] = perPage */
};
static const ProtobufCIntRange saved_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor saved_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SavedResult",
  "SavedResult",
  "SavedResult",
  "",
  sizeof(SavedResult),
  2,
  saved_result__field_descriptors,
  saved_result__field_indices_by_name,
  1,  saved_result__number_ranges,
  (ProtobufCMessageInit) saved_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor saved_node__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedNode, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SavedNode, data),
    &saved_node_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commentData",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SavedNode, commentdata),
    &saved_comment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resultData",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SavedNode, resultdata),
    &saved_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned saved_node__field_indices_by_name[] = {
  2,   /* field[2] = commentData */
  1,   /* field[1] = data */
  0,   /* field[0] = id */
  3,   /* field[3] = resultData */
};
static const ProtobufCIntRange saved_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor saved_node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SavedNode",
  "SavedNode",
  "SavedNode",
  "",
  sizeof(SavedNode),
  4,
  saved_node__field_descriptors,
  saved_node__field_indices_by_name,
  1,  saved_node__number_ranges,
  (ProtobufCMessageInit) saved_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor saved_connection__field_descriptors[2] =
{
  {
    "fromId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedConnection, fromid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "toId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SavedConnection, toid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned saved_connection__field_indices_by_name[] = {
  0,   /* field[0] = fromId */
  1,   /* field[1] = toId */
};
static const ProtobufCIntRange saved_connection__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor saved_connection__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SavedConnection",
  "SavedConnection",
  "SavedConnection",
  "",
  sizeof(SavedConnection),
  2,
  saved_connection__field_descriptors,
  saved_connection__field_indices_by_name,
  1,  saved_connection__number_ranges,
  (ProtobufCMessageInit) saved_connection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor saved_bucket__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SavedBucket, type),
    &saved_node_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SavedBucket, n_nodes),
    offsetof(SavedBucket, nodes),
    &saved_node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned saved_bucket__field_indices_by_name[] = {
  1,   /* field[1] = nodes */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange saved_bucket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor saved_bucket__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SavedBucket",
  "SavedBucket",
  "SavedBucket",
  "",
  sizeof(SavedBucket),
  2,
  saved_bucket__field_descriptors,
  saved_bucket__field_indices_by_name,
  1,  saved_bucket__number_ranges,
  (ProtobufCMessageInit) saved_bucket__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor saved_preset__field_descriptors[2] =
{
  {
    "buckets",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SavedPreset, n_buckets),
    offsetof(SavedPreset, buckets),
    &saved_bucket__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connections",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SavedPreset, n_connections),
    offsetof(SavedPreset, connections),
    &saved_connection__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned saved_preset__field_indices_by_name[] = {
  0,   /* field[0] = buckets */
  1,   /* field[1] = connections */
};
static const ProtobufCIntRange saved_preset__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor saved_preset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SavedPreset",
  "SavedPreset",
  "SavedPreset",
  "",
  sizeof(SavedPreset),
  2,
  saved_preset__field_descriptors,
  saved_preset__field_indices_by_name,
  1,  saved_preset__number_ranges,
  (ProtobufCMessageInit) saved_preset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor saved_globals__field_descriptors[1] =
{
  {
    "disclaimer",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SavedGlobals, disclaimer),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned saved_globals__field_indices_by_name[] = {
  0,   /* field[0] = disclaimer */
};
static const ProtobufCIntRange saved_globals__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor saved_globals__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SavedGlobals",
  "SavedGlobals",
  "SavedGlobals",
  "",
  sizeof(SavedGlobals),
  1,
  saved_globals__field_descriptors,
  saved_globals__field_indices_by_name,
  1,  saved_globals__number_ranges,
  (ProtobufCMessageInit) saved_globals__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue saved_node_type__enum_values_by_number[12] =
{
  { "NCOMMENT", "SAVED_NODE_TYPE__NCOMMENT", 0 },
  { "NCUBE", "SAVED_NODE_TYPE__NCUBE", 1 },
  { "NTIER", "SAVED_NODE_TYPE__NTIER", 2 },
  { "NCATEGORY", "SAVED_NODE_TYPE__NCATEGORY", 3 },
  { "NSTAT", "SAVED_NODE_TYPE__NSTAT", 4 },
  { "NAMOUNT", "SAVED_NODE_TYPE__NAMOUNT", 5 },
  { "NRESULT", "SAVED_NODE_TYPE__NRESULT", 6 },
  { "NSPLIT", "SAVED_NODE_TYPE__NSPLIT", 7 },
  { "NLEVEL", "SAVED_NODE_TYPE__NLEVEL", 8 },
  { "NREGION", "SAVED_NODE_TYPE__NREGION", 9 },
  { "NOR", "SAVED_NODE_TYPE__NOR", 10 },
  { "NAND", "SAVED_NODE_TYPE__NAND", 11 },
};
static const ProtobufCIntRange saved_node_type__value_ranges[] = {
{0, 0},{0, 12}
};
static const ProtobufCEnumValueIndex saved_node_type__enum_values_by_name[12] =
{
  { "NAMOUNT", 5 },
  { "NAND", 11 },
  { "NCATEGORY", 3 },
  { "NCOMMENT", 0 },
  { "NCUBE", 1 },
  { "NLEVEL", 8 },
  { "NOR", 10 },
  { "NREGION", 9 },
  { "NRESULT", 6 },
  { "NSPLIT", 7 },
  { "NSTAT", 4 },
  { "NTIER", 2 },
};
const ProtobufCEnumDescriptor saved_node_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SavedNodeType",
  "SavedNodeType",
  "SavedNodeType",
  "",
  12,
  saved_node_type__enum_values_by_number,
  12,
  saved_node_type__enum_values_by_name,
  1,
  saved_node_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
