/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cubecalc.proto */

#ifndef PROTOBUF_C_cubecalc_2eproto__INCLUDED
#define PROTOBUF_C_cubecalc_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SavedRect SavedRect;
typedef struct _SavedNodeData SavedNodeData;
typedef struct _SavedComment SavedComment;
typedef struct _SavedResult SavedResult;
typedef struct _SavedNode SavedNode;
typedef struct _SavedConnection SavedConnection;
typedef struct _SavedBucket SavedBucket;
typedef struct _SavedPreset SavedPreset;
typedef struct _SavedGlobals SavedGlobals;


/* --- enums --- */

typedef enum _SavedNodeType {
  SAVED_NODE_TYPE__NCOMMENT = 0,
  SAVED_NODE_TYPE__NCUBE = 1,
  SAVED_NODE_TYPE__NTIER = 2,
  SAVED_NODE_TYPE__NCATEGORY = 3,
  SAVED_NODE_TYPE__NSTAT = 4,
  SAVED_NODE_TYPE__NAMOUNT = 5,
  SAVED_NODE_TYPE__NRESULT = 6,
  SAVED_NODE_TYPE__NSPLIT = 7,
  SAVED_NODE_TYPE__NLEVEL = 8,
  SAVED_NODE_TYPE__NREGION = 9,
  SAVED_NODE_TYPE__NOR = 10,
  SAVED_NODE_TYPE__NAND = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SAVED_NODE_TYPE)
} SavedNodeType;

/* --- messages --- */

struct  _SavedRect
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
  int32_t w;
  int32_t h;
};
#define SAVED_RECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&saved_rect__descriptor) \
    , 0, 0, 0, 0 }


struct  _SavedNodeData
{
  ProtobufCMessage base;
  SavedRect *bounds;
  int32_t valuelo;
  int32_t valuehi;
};
#define SAVED_NODE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&saved_node_data__descriptor) \
    , NULL, 0, 0 }


struct  _SavedComment
{
  ProtobufCMessage base;
  char *text;
};
#define SAVED_COMMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&saved_comment__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _SavedResult
{
  ProtobufCMessage base;
  int32_t page;
  int32_t perpage;
};
#define SAVED_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&saved_result__descriptor) \
    , 0, 0 }


struct  _SavedNode
{
  ProtobufCMessage base;
  int32_t id;
  SavedNodeData *data;
  SavedComment *commentdata;
  SavedResult *resultdata;
};
#define SAVED_NODE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&saved_node__descriptor) \
    , 0, NULL, NULL, NULL }


struct  _SavedConnection
{
  ProtobufCMessage base;
  int32_t fromid;
  int32_t toid;
};
#define SAVED_CONNECTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&saved_connection__descriptor) \
    , 0, 0 }


struct  _SavedBucket
{
  ProtobufCMessage base;
  SavedNodeType type;
  size_t n_nodes;
  SavedNode **nodes;
};
#define SAVED_BUCKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&saved_bucket__descriptor) \
    , SAVED_NODE_TYPE__NCOMMENT, 0,NULL }


struct  _SavedPreset
{
  ProtobufCMessage base;
  size_t n_buckets;
  SavedBucket **buckets;
  size_t n_connections;
  SavedConnection **connections;
};
#define SAVED_PRESET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&saved_preset__descriptor) \
    , 0,NULL, 0,NULL }


struct  _SavedGlobals
{
  ProtobufCMessage base;
  char *disclaimer;
};
#define SAVED_GLOBALS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&saved_globals__descriptor) \
    , (char *)protobuf_c_empty_string }


/* SavedRect methods */
void   saved_rect__init
                     (SavedRect         *message);
size_t saved_rect__get_packed_size
                     (const SavedRect   *message);
size_t saved_rect__pack
                     (const SavedRect   *message,
                      uint8_t             *out);
size_t saved_rect__pack_to_buffer
                     (const SavedRect   *message,
                      ProtobufCBuffer     *buffer);
SavedRect *
       saved_rect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   saved_rect__free_unpacked
                     (SavedRect *message,
                      ProtobufCAllocator *allocator);
/* SavedNodeData methods */
void   saved_node_data__init
                     (SavedNodeData         *message);
size_t saved_node_data__get_packed_size
                     (const SavedNodeData   *message);
size_t saved_node_data__pack
                     (const SavedNodeData   *message,
                      uint8_t             *out);
size_t saved_node_data__pack_to_buffer
                     (const SavedNodeData   *message,
                      ProtobufCBuffer     *buffer);
SavedNodeData *
       saved_node_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   saved_node_data__free_unpacked
                     (SavedNodeData *message,
                      ProtobufCAllocator *allocator);
/* SavedComment methods */
void   saved_comment__init
                     (SavedComment         *message);
size_t saved_comment__get_packed_size
                     (const SavedComment   *message);
size_t saved_comment__pack
                     (const SavedComment   *message,
                      uint8_t             *out);
size_t saved_comment__pack_to_buffer
                     (const SavedComment   *message,
                      ProtobufCBuffer     *buffer);
SavedComment *
       saved_comment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   saved_comment__free_unpacked
                     (SavedComment *message,
                      ProtobufCAllocator *allocator);
/* SavedResult methods */
void   saved_result__init
                     (SavedResult         *message);
size_t saved_result__get_packed_size
                     (const SavedResult   *message);
size_t saved_result__pack
                     (const SavedResult   *message,
                      uint8_t             *out);
size_t saved_result__pack_to_buffer
                     (const SavedResult   *message,
                      ProtobufCBuffer     *buffer);
SavedResult *
       saved_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   saved_result__free_unpacked
                     (SavedResult *message,
                      ProtobufCAllocator *allocator);
/* SavedNode methods */
void   saved_node__init
                     (SavedNode         *message);
size_t saved_node__get_packed_size
                     (const SavedNode   *message);
size_t saved_node__pack
                     (const SavedNode   *message,
                      uint8_t             *out);
size_t saved_node__pack_to_buffer
                     (const SavedNode   *message,
                      ProtobufCBuffer     *buffer);
SavedNode *
       saved_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   saved_node__free_unpacked
                     (SavedNode *message,
                      ProtobufCAllocator *allocator);
/* SavedConnection methods */
void   saved_connection__init
                     (SavedConnection         *message);
size_t saved_connection__get_packed_size
                     (const SavedConnection   *message);
size_t saved_connection__pack
                     (const SavedConnection   *message,
                      uint8_t             *out);
size_t saved_connection__pack_to_buffer
                     (const SavedConnection   *message,
                      ProtobufCBuffer     *buffer);
SavedConnection *
       saved_connection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   saved_connection__free_unpacked
                     (SavedConnection *message,
                      ProtobufCAllocator *allocator);
/* SavedBucket methods */
void   saved_bucket__init
                     (SavedBucket         *message);
size_t saved_bucket__get_packed_size
                     (const SavedBucket   *message);
size_t saved_bucket__pack
                     (const SavedBucket   *message,
                      uint8_t             *out);
size_t saved_bucket__pack_to_buffer
                     (const SavedBucket   *message,
                      ProtobufCBuffer     *buffer);
SavedBucket *
       saved_bucket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   saved_bucket__free_unpacked
                     (SavedBucket *message,
                      ProtobufCAllocator *allocator);
/* SavedPreset methods */
void   saved_preset__init
                     (SavedPreset         *message);
size_t saved_preset__get_packed_size
                     (const SavedPreset   *message);
size_t saved_preset__pack
                     (const SavedPreset   *message,
                      uint8_t             *out);
size_t saved_preset__pack_to_buffer
                     (const SavedPreset   *message,
                      ProtobufCBuffer     *buffer);
SavedPreset *
       saved_preset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   saved_preset__free_unpacked
                     (SavedPreset *message,
                      ProtobufCAllocator *allocator);
/* SavedGlobals methods */
void   saved_globals__init
                     (SavedGlobals         *message);
size_t saved_globals__get_packed_size
                     (const SavedGlobals   *message);
size_t saved_globals__pack
                     (const SavedGlobals   *message,
                      uint8_t             *out);
size_t saved_globals__pack_to_buffer
                     (const SavedGlobals   *message,
                      ProtobufCBuffer     *buffer);
SavedGlobals *
       saved_globals__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   saved_globals__free_unpacked
                     (SavedGlobals *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SavedRect_Closure)
                 (const SavedRect *message,
                  void *closure_data);
typedef void (*SavedNodeData_Closure)
                 (const SavedNodeData *message,
                  void *closure_data);
typedef void (*SavedComment_Closure)
                 (const SavedComment *message,
                  void *closure_data);
typedef void (*SavedResult_Closure)
                 (const SavedResult *message,
                  void *closure_data);
typedef void (*SavedNode_Closure)
                 (const SavedNode *message,
                  void *closure_data);
typedef void (*SavedConnection_Closure)
                 (const SavedConnection *message,
                  void *closure_data);
typedef void (*SavedBucket_Closure)
                 (const SavedBucket *message,
                  void *closure_data);
typedef void (*SavedPreset_Closure)
                 (const SavedPreset *message,
                  void *closure_data);
typedef void (*SavedGlobals_Closure)
                 (const SavedGlobals *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    saved_node_type__descriptor;
extern const ProtobufCMessageDescriptor saved_rect__descriptor;
extern const ProtobufCMessageDescriptor saved_node_data__descriptor;
extern const ProtobufCMessageDescriptor saved_comment__descriptor;
extern const ProtobufCMessageDescriptor saved_result__descriptor;
extern const ProtobufCMessageDescriptor saved_node__descriptor;
extern const ProtobufCMessageDescriptor saved_connection__descriptor;
extern const ProtobufCMessageDescriptor saved_bucket__descriptor;
extern const ProtobufCMessageDescriptor saved_preset__descriptor;
extern const ProtobufCMessageDescriptor saved_globals__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_cubecalc_2eproto__INCLUDED */
