#include "../main.c"
#include "generated_impl.c"
#include "graphcalc_impl.c"
#include "graph_impl.c"
#include "humanize_impl.c"
#include "nuklear_impl.c"
#include "serialization_impl.c"
#include "utils_impl.c"
