#!/usr/bin/env python3

import sys
sys.path.append("./cubecalc/src/")
from common import *

print(f"/* generated by {sys.argv[0]}, do not edit */")
for en in [Cube, Category, Line]:
  n = en.__name__.lower()
  print(f"char const* {n}Names[] = {{")
  vals = [x for x in en]
  if en == Category:
    for x in vals:
      print(f"  \"{category_name(x)}\",")
  else:
    for x in vals:
      print(f"  \"{x.name.lower()}\",")
  print("};")
  print(f"int {n}Values[] = {{")
  for x in vals:
    print(f"  {x.value},")
  print("};")
  for i, x in enumerate(vals):
    print(f"#define {x.name} {i}")
