/* generated by ./generate_c.py, do not edit */
char const* cubeNames[] = {
  "red",
  "meister",
  "master",
  "occult",
  "black",
  "violet",
  "equality",
  "bonus",
  "uni",
};
int cubeValues[] = {
  1,
  2,
  4,
  8,
  16,
  32,
  64,
  128,
  256,
};
#define RED 0
#define MEISTER 1
#define MASTER 2
#define OCCULT 3
#define BLACK 4
#define VIOLET 5
#define EQUALITY 6
#define BONUS 7
#define UNI 8
char const* categoryNames[] = {
  "weapon",
  "emblem",
  "2ndary excl. force shield/soul ring",
  "force shield/soul ring",
  "hat",
  "top/overall",
  "bottom",
  "shoe",
  "glove",
  "cape/belt/shoulder",
  "accessory (face/eye/ring/ear/pend)",
  "heart/badge",
  "combos",
  "name",
  "default_cube",
};
int categoryValues[] = {
  1,
  2,
  4,
  8,
  16,
  32,
  64,
  128,
  256,
  512,
  1024,
  2048,
  4096,
  8192,
  16384,
};
#define WEAPON 0
#define EMBLEM 1
#define SECONDARY 2
#define FORCE_SHIELD_SOUL_RING 3
#define HAT 4
#define TOP_OVERALL 5
#define BOTTOM 6
#define SHOE 7
#define GLOVE 8
#define CAPE_BELT_SHOULDER 9
#define FACE_EYE_RING_EARRING_PENDANT 10
#define HEART_BADGE 11
#define COMBOS 12
#define NAME 13
#define DEFAULT_CUBE 14
char const* lineNames[] = {
  "boss_30",
  "boss_35",
  "boss_40",
  "ied_15",
  "ied_30",
  "ied_35",
  "ied_40",
  "att",
  "any",
  "mainstat",
  "allstat",
  "hp",
  "cooldown_1",
  "cooldown_2",
  "critdmg",
  "meso",
  "drop",
  "invin",
  "decent_speed_infusion",
  "decent_sharp_eyes",
  "decent_combat_orders",
  "flat_att",
  "flat_mainstat",
  "flat_allstat",
  "flat_hp",
  "lines",
};
int lineValues[] = {
  1,
  2,
  4,
  8,
  16,
  32,
  64,
  128,
  256,
  512,
  1024,
  2048,
  4096,
  8192,
  16384,
  32768,
  65536,
  131072,
  262144,
  524288,
  1048576,
  2097152,
  4194304,
  8388608,
  16777216,
  33554432,
};
#define BOSS_30 0
#define BOSS_35 1
#define BOSS_40 2
#define IED_15 3
#define IED_30 4
#define IED_35 5
#define IED_40 6
#define ATT 7
#define ANY 8
#define MAINSTAT 9
#define ALLSTAT 10
#define HP 11
#define COOLDOWN_1 12
#define COOLDOWN_2 13
#define CRITDMG 14
#define MESO 15
#define DROP 16
#define INVIN 17
#define DECENT_SPEED_INFUSION 18
#define DECENT_SHARP_EYES 19
#define DECENT_COMBAT_ORDERS 20
#define FLAT_ATT 21
#define FLAT_MAINSTAT 22
#define FLAT_ALLSTAT 23
#define FLAT_HP 24
#define LINES 25
