name: "Deployment"

concurrency:
  group: nightly
  cancel-in-progress: true

on:
  pull_request:
  push:

jobs:
  build-appimage:
    strategy:
      matrix:
        ARCH: [x86_64]

    name: Desktop ${{ matrix.ARCH }}
    runs-on: ubuntu-latest
    env:
      ARCH: ${{ matrix.ARCH }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (x86_64)
      if: matrix.ARCH == 'x86_64'
      run: |
        sudo apt-get update
        sudo apt-get install -y meson libglfw3-dev
    - name: Build AppImage (x86_64)
      if: matrix.ARCH == 'x86_64'
      run: |
        cd src
        ./appimage.sh
    - name: Archive AppImage
      uses: actions/upload-artifact@v3
      with:
        name: AppImage
        path: src/cubecalc-ui-*.AppImage

  build-nix-emscripten:
    name: Cachix, Web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: lolisamurai
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build and cache nix packages
      run: src/cachix-push.sh
    - name: Package emscripten build
      run: |
        mv -v result cubecalc-ui-web
        7z a cubecalc-ui-web.zip cubecalc-ui-web/
    - name: Archive web build
      uses: actions/upload-artifact@v3
      with:
        name: web
        path: cubecalc-ui-web.zip

  upload:
    name: Create release and upload artifacts
    needs:
      - build-appimage
      - build-nix-emscripten
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
          GITHUB_CONTINUOUS_RELEASE_NAME: nightly (automaticaly built on every change)
          GITHUB_CONTINUOUS_RELEASE_TAG: 9999.9999.9999-nightly
        run: |
          wget -q https://github.com/Francesco149/cubecalc-ui/releases/download/0.0.0-pyuploadtool-2022-10-17/pyuploadtool-x86_64.AppImage
          wget -q https://github.com/Francesco149/cubecalc-ui/releases/download/0.0.0-pyuploadtool-2022-10-17/pyuploadtool-x86_64.AppImage.sum
          sha512sum -c pyuploadtool-x86_64.AppImage.sum &&
          chmod +x pyuploadtool-x86_64.AppImage &&
          ./pyuploadtool-x86_64.AppImage AppImage/cubecalc-ui*.AppImage web/cubecalc-ui-web.zip
